create table if not exists Student
(
    id         int generated by default as identity primary key,
    first_name varchar(255),
    last_name  varchar(255),
    grade      varchar(255),
    comment    varchar(255),
    email      varchar(255)
);


insert into Student (id, first_name, last_name, grade, comment, email)
values (1, 'Іван', 'Пес', '11', 'Відмінник', 'ivan@jmail.com'),
       (2, 'Василина', 'Сало', '11', 'Добре вчиться', 'vasylyna@jmail.com'),
       (3, 'Олександр', 'Криса', '11', 'Має потенціал', 'oleksandr@jmail.com'),
       (4, 'Анна', 'Вафля', '11', 'Відмінниця, активістка', 'anna@jmail.com'),
       (5, 'Дмитро', 'Жук', '9', 'Безнадійний', 'dmytro@jmail.com'),
       (6, 'Тетяна', 'Голубець', '9', 'Переможець олімпіад', 'tetiana@jmail.com'),
       (7, 'Олег', 'Князь', '9', 'Покращує свої знання з математики', 'oleg@jmail.com'),
       (8, 'Софія', 'Синяк', '9', 'Потребує додаткових занять', 'sofia@jmail.com'),
       (9, 'Василь', 'Стакан', '7', 'Дуже зацікавлений у фізиці', 'vasyl@jmail.com'),
       (10, 'Юлія', 'Вареник', '7', 'Лідер класу, відмінна академічна успішність', 'yulia@jmail.com'),
       (11, 'Микита', 'Шостий', '7', 'Працює над проектом з екології', 'petro@jmail.com');


create table if not exists Topic
(
    id    int generated by default as identity primary key,
    title varchar(512)
);


insert into Topic (id, title)
values (19, 'Числові множини'),
       (20, 'Подільність'),
       (21, 'Задачі на рух, відсотки...'),
       (23, 'Дробові вирази'),
       (24, 'Степінь'),
       (25, 'Арифметичний корінь'),
       (26, 'Логарифм'),
       (27, 'Лінійні рівняння'),
       (28, 'Квадратні рівняння'),
       (29, 'Дробово-раціональні рівняння'),
       (30, 'Рівняння з модулем');







