
create table if not exists Student(
    id int generated by default as identity primary key,
    first_name varchar(255),
    last_name varchar(255),
    grade varchar(255),
    comment varchar(255),
    email varchar(255)
);

insert into Student (first_name, last_name, grade, comment, email) values ('Іван', 'Пес', 'A', 'Відмінник', 'ivan@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Василина', 'Сало', 'B', 'Добре вчиться', 'vasylyna@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Олександр', 'Криса', 'C', 'Має потенціал', 'oleksandr@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Анна', 'Вафля', 'A', 'Відмінниця, активістка', 'anna@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Дмитро', 'Жук', 'B', 'Безнадійний', 'dmytro@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Тетяна', 'Голубець', 'A', 'Переможець олімпіад', 'tetiana@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Олег', 'Князь', 'B', 'Покращує свої знання з математики', 'oleg@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Софія', 'Синяк', 'C', 'Потребує додаткових занять', 'sofia@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Василь', 'Стакан', 'B', 'Дуже зацікавлений у фізиці', 'vasyl@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Юлія', 'Вареник', 'A', 'Лідер класу, відмінна академічна успішність', 'yulia@jmail.com');
insert into Student (first_name, last_name, grade, comment, email) values ('Микита', 'Шостий', 'C', 'Працює над проектом з екології', 'petro@jmail.com');



