DELETE FROM exam_tasks;
DELETE FROM exam_student;
DELETE FROM task;
DELETE FROM student;

DELETE FROM exam;
DELETE FROM topic;
DELETE FROM zno;

DROP TABLE IF EXISTS exam_tasks;
DROP TABLE IF EXISTS exam_student;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS exam;
DROP TABLE IF EXISTS topic;
DROP TABLE IF EXISTS zno;
