CREATE TABLE IF NOT EXISTS zno
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    year VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS topic
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(512)
);

INSERT INTO zno (name, year)
VALUES ('ЗНО з математики 2021', '2021');
INSERT INTO topic (title)
VALUES ('Математика'),
       ('Фізика');

CREATE TABLE IF NOT EXISTS exam
(
    id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name       TEXT,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    grade      VARCHAR(255),
    comment    VARCHAR(255),
    email      VARCHAR(255)
);

INSERT INTO exam (name, created_at)
VALUES ('Перший екзамен', '2023-01-10 10:00:00'),
       ('Другий екзамен', '2023-02-15 10:00:00'),
       ('Третій екзамен', '2023-03-20 10:00:00');

INSERT INTO student (first_name, last_name, grade, comment, email)
VALUES ('Іван', 'Пес', '11', 'Відмінник', 'ivan@example.com'),
       ('Ольга', 'Коваль', '10', 'Добре вчиться', 'olga@example.com');

CREATE TABLE IF NOT EXISTS task
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id   INTEGER REFERENCES topic,
    image_path TEXT,
    level      VARCHAR(255),
    image_text TEXT,
    answer     VARCHAR(255),
    title      VARCHAR(255),
    zno_id     INTEGER REFERENCES zno
);

CREATE TABLE IF NOT EXISTS exam_student
(
    student_id INTEGER REFERENCES student,
    exam_id    INTEGER REFERENCES exam
);

CREATE TABLE IF NOT EXISTS exam_tasks
(
    task_id INTEGER REFERENCES task,
    exam_id INTEGER REFERENCES exam
);

insert into task(topic_id, image_path, level, image_text, answer, title, zno_id)
values ((SELECT id FROM topic WHERE title = 'Математика'), '/path/to/image1.jpg', '1', '', '', 'Модуль',
        (SELECT id FROM zno WHERE year = '2021')),
       ((SELECT id FROM topic WHERE title = 'Фізика'), '/path/to/image1.jpg', '1', '', '', 'Планіметрія',
        (SELECT id FROM zno WHERE year = '2021'));

INSERT INTO exam_tasks (task_id, exam_id)
VALUES (1, 1),
       (2, 1);