create table if not exists Zno
(
    id   int generated by default as identity primary key,
    name text,
    year varchar(128)
);

create table if not exists Topic
(
    id    int generated by default as identity primary key,
    title varchar(512)
);

insert into Topic (title)
values ('Числові множини'),
       ('Подільність'),
       ('Задачі на рух, відсотки...');

INSERT INTO Zno (name, year)
VALUES ('ЗНО онлайн 2021 року з математики – демонстраційний варіант', '2021'),
       ('ЗНО онлайн 2020 року з математики – основна сесія', '2020'),
       ('ЗНО онлайн 2020 року з математики – додаткова сесія', '2020'),
       ('ЗНО онлайн 2020 року з математики – пробний тест', '2020'),
       ('ЗНО онлайн 2019 року з математики – основна сесія', '2019'),
       ('ЗНО онлайн 2019 року з математики – додаткова сесія', '2019'),
       ('ЗНО онлайн 2019 року з математики – пробний тест', '2019'),
       ('ЗНО онлайн 2018 року з математики – основна сесія', '2018'),
       ('ЗНО онлайн 2018 року з математики – додаткова сесія', '2018'),
       ('ЗНО онлайн 2018 року з математики – пробний тест', '2018'),
       ('ЗНО онлайн 2017 року з математики – основна сесія', '2017');


CREATE TABLE task
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id   INTEGER,
    image_path TEXT,
    level      varchar(255),
    image_text TEXT,
    answer     VARCHAR(255),
    title      VARCHAR(255),
    zno_id     INTEGER
);


INSERT INTO task (topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (1, '/path/to/image1.jpg', '1', '<p>HTML Text 1</p>', 'A', 'Task Title 1', 1);
INSERT INTO task (topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (2, '/path/to/image2.jpg', '2', '<p>HTML Text 2</p>', 'B', 'Task Title 2', 1);
INSERT INTO task (topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (3, '/path/to/image3.jpg', '3', '<p>HTML Text 3</p>', 'C', 'Task Title 3', 2);

