create table if not exists task
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id   INTEGER,
    image_path TEXT,
    level      varchar(255),
    image_text TEXT,
    answer     VARCHAR(255),
    title      VARCHAR(255),
    zno_id     INTEGER
);

create table if not exists Zno
(
    id   int generated by default as identity primary key,
    name text,
    year varchar(128)
);

create table if not exists Topic
(
    id    int generated by default as identity primary key,
    title varchar(512)
);

create table if not exists Student
(
    id         int generated by default as identity primary key,
    first_name varchar(255),
    last_name  varchar(255),
    grade      varchar(255),
    comment    varchar(255),
    email      varchar(255)
);

create table if not exists exam
(
    id         integer generated always as identity
            primary key,
    name       text,
    created_at timestamp
);

create table if not exists exam_student
(
    student_id integer,
    exam_id    integer
);

create table if not exists exam_tasks
(
    task_id integer
            references task,
    exam_id integer
            references exam
);

insert into Student (id, first_name, last_name, grade, comment, email)
values (1, 'Іван', 'Пес', '11', 'Відмінник', 'ivan@jmail.com'),
       (2, 'Василина', 'Сало', '11', 'Добре вчиться', 'vasylyna@jmail.com'),
       (3, 'Олександр', 'Криса', '11', 'Має потенціал', 'oleksandr@jmail.com'),
       (4, 'Анна', 'Вафля', '11', 'Відмінниця, активістка', 'anna@jmail.com'),
       (5, 'Дмитро', 'Жук', '9', 'Безнадійний', 'dmytro@jmail.com'),
       (6, 'Тетяна', 'Голубець', '9', 'Переможець олімпіад', 'tetiana@jmail.com'),
       (7, 'Олег', 'Князь', '9', 'Покращує свої знання з математики', 'oleg@jmail.com'),
       (8, 'Софія', 'Синяк', '9', 'Потребує додаткових занять', 'sofia@jmail.com'),
       (9, 'Василь', 'Стакан', '7', 'Дуже зацікавлений у фізиці', 'vasyl@jmail.com'),
       (10, 'Юлія', 'Вареник', '7', 'Лідер класу, відмінна академічна успішність', 'yulia@jmail.com'),
       (11, 'Микита', 'Шостий', '7', 'Працює над проектом з екології', 'petro@jmail.com');

insert into Topic (title)
values ('Числові множини'),
       ('Подільність'),
       ('Задачі на рух, відсотки...');

INSERT INTO Zno (name, year)
VALUES ('ЗНО онлайн 2021 року з математики – демонстраційний варіант', '2021'),
       ('ЗНО онлайн 2020 року з математики – основна сесія', '2020'),
       ('ЗНО онлайн 2020 року з математики – додаткова сесія', '2020'),
       ('ЗНО онлайн 2020 року з математики – пробний тест', '2020'),
       ('ЗНО онлайн 2019 року з математики – основна сесія', '2019'),
       ('ЗНО онлайн 2019 року з математики – додаткова сесія', '2019'),
       ('ЗНО онлайн 2019 року з математики – пробний тест', '2019'),
       ('ЗНО онлайн 2018 року з математики – основна сесія', '2018'),
       ('ЗНО онлайн 2018 року з математики – додаткова сесія', '2018'),
       ('ЗНО онлайн 2018 року з математики – пробний тест', '2018'),
       ('ЗНО онлайн 2017 року з математики – основна сесія', '2017');

INSERT INTO task (id, topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (101, 1, '/path/to/image1.jpg', '1', '<p>HTML Text 1</p>', 'A', 'Числові множини', 1);
INSERT INTO task (id, topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (102, 2, '/path/to/image2.jpg', '2', '<p>HTML Text 2</p>', 'B', 'Подільність', 1);
INSERT INTO task (id, topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (103, 2, '/path/to/image3.jpg', '3', '<p>HTML Text 3</p>', 'C', 'Подільність', 2);
INSERT INTO task (id, topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (104, 3, '/path/to/image3.jpg', '3', '<p>HTML Text 3</p>', 'C', 'Задачі на рух, відсотки...', 2);
INSERT INTO task (id, topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (105, 2, '/path/to/image3.jpg', '3', '<p>HTML Text 3</p>', 'C', 'Подільність', 2);
INSERT INTO task (id, topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (106, 1, '/path/to/image3.jpg', '3', '<p>HTML Text 3</p>', 'C', 'Числові множини', 2);
INSERT INTO task (id, topic_id, image_path, level, image_text, answer, title, zno_id) VALUES (107, 3, '/path/to/image3.jpg', '3', '<p>HTML Text 3</p>', 'C', 'Задачі на рух, відсотки...', 2);


insert into exam (name) values ('Перший екзамен');
insert into exam (name) values ('Другий екзамен');
insert into exam (name) values ('Третій екзамен');

insert into exam_student(student_id, exam_id) values (1, 1);
insert into exam_tasks(task_id, exam_id) VALUES (101, 1);
